version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
  
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Backend Service
  backend:
    image: your-dockerhub-username/backend-image:latest
    container_name: backend
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
      - SECRET_KEY="your-secret-key"   
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GEMINI_API_KEY=AIzaSyA74a9ZGgZ0tBUl0JF-VPRx91Ye75Ul_9M
      - OPEN_WEATHER_API_KEY=ec94fe473b80673dcd3b24632c85ec57
      
      # Add other environment variables for your backend here
    depends_on:
      - mongodb
    ports:
      - "8000:8000"  # Adjust the port as needed
    networks:
      - app-network

  # Frontend Service
  frontend:
    image: haddadmed555/fin-ghadi-webe-app:1.0
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000  # Adjust the URL as needed
      # Add other environment variables for your frontend here
    depends_on:
      - backend
    ports:
      - "3000:3000"  # Adjust the port as needed
    networks:
      - app-network

# Volumes
volumes:
  mongodb_data:

# Networks
networks:
  app-network:
    driver: bridge